---
dependencies:
  - name: redis
    version: 6.4.4
    repository: "@stable"
  - name: gcloud-sqlproxy
    version: 0.6.0
    repository: "@stable"
    condition: cloudsql.enabled
    alias: sqlproxy
