---
dependencies:
  - name: redis
    version: 6.4.4
    repository: "@stable"
  - name: gcloud-sqlproxy
    version: 0.12.0
    repository: "@rimusz"
    condition: cloudsql.enabled
    alias: sqlproxy
