dependencies:
  - name: redis
    version: 1.1.19
    repository: "@stable"
  - name: mariadb
    version: 2.1.14
    repository: "@stable"
    condition: mariadb.enabled
    tags:
      - wordpress-database
  - name: gcloud-sqlproxy
    version: 0.3.0
    repository: "@stable"
    condition: cloudsql.enabled
    alias: sqlproxy
