dependencies:
  - name: redis
    version: 1.1.12
    repository: "@stable"
  - name: mariadb
    version: 2.1.1
    repository: "@stable"
    condition: mariadb.enabled
    tags:
      - wordpress-database
