apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-openresty-autoscaler
  labels:
    app: {{ .Release.Name }}-wordpress
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ template "openresty.fullname" . }}
  minReplicas: {{ .Values.openresty.minReplicaCount }}
  maxReplicas: {{ .Values.openresty.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.openresty.targetCPUUtilizationPercentage }}  # * php.resources.requests. 1000% of 50m = .5 CPU