---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "generic.fullname" . }}-redis
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: proxy
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
    - from:
        - podSelector:
            matchLabels:
              component: php
              release: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: 6379
---