---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "generic.fullname" . }}-openresty
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      component: proxy
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: nginx-ingress
              app.kubernetes.io/name: ingress-nginx
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nginx-ingress
      ports:
        - protocol: TCP
          port: 80
---