{{- if .Values.nginxingresstls.enabled }}
{{- $fullName := include "openresty.fullname" . -}}
apiVersion:  networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-nginx-wtls
  labels:
    app: {{ .Release.Name }}-wordpress
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.nginxingresstls.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  {{- if .Values.nginxingresstls.hosts }}
  {{- range .Values.nginxingresstls.hosts }}
  - hosts:
    - {{ .name }}
  {{- if .tls }}
    secretName: {{ .name }}-wtls
  {{- end }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /{{ .Values.hostpath | default "" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- if eq .Values.environment "production" }}
    - host: {{ .Values.hostnameProduction }}
      http:
        paths:
          - path: /{{ .Values.hostpathProduction | default .Values.hostpath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- end }}
{{- end }}
