{{- if .Values.nginxingress.enabled -}}
{{- $fullName := include "openresty.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-nginx
  labels:
    app: {{ .Release.Name }}-wordpress
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.nginxingress.annotations }}
  annotations:
    {{- if or (eq .oauth "gp") (eq .oauth "p4") (eq .oauth "ops") }}
    nginx.ingress.kubernetes.io/auth-url: https://nginx-oauth.greenpeace.org/oauth2/{{ .oauth }}/auth
    nginx.ingress.kubernetes.io/auth-signin: https://nginx-oauth.greenpeace.org/oauth2/{{ .oauth }}/start?rd=https://$host$uri
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-Email, X-Auth-Request-User
    {{- end }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.nginxingress.ingressClassName }}
  tls:
  {{- if .Values.nginxingress.hosts }}
  {{- range .Values.nginxingress.hosts }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .name }}-tls
  {{- end }}
  {{- end }}
  {{- else }}
  - hosts:
    - {{ .Values.hostname }}
  {{- end }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /{{ .Values.hostpath | default "" }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
