{{- if .Values.php.persistence.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-pvc-wordfence"
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: {{ .Values.php.persistence.class | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
{{- end -}}
