{{- if .Values.wp.stateless.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-stateless"
  labels:
    app: "{{ .Release.Name }}"
    chart: {{ template "wordpress.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  credentials.json: |-
    {{ .Values.wp.stateless.serviceAccountKey }}
{{- end -}}
