{{- if .Values.openresty.geoip.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-maxmind"
  labels:
    app: "{{ .Release.Name }}-openresty"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  accountid: {{ .Values.maxmind.accountid | quote }}
  license: {{ .Values.maxmind.license | quote }}
{{- end -}}
