apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-keysalt"
  labels:
    app: "{{ .Release.Name }}"
    chart: {{ template "wordpress.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    authKey: {{ .Values.wp.authKey | quote }}
    authSalt: {{ .Values.wp.authSalt | quote }}
    loggedInKey: {{ .Values.wp.loggedInKey | quote }}
    loggedInSalt: {{ .Values.wp.loggedInSalt | quote }}
    nonceKey: {{ .Values.wp.nonceKey | quote }}
    nonceSalt: {{ .Values.wp.nonceSalt | quote }}
    secureAuthKey: {{ .Values.wp.secureAuthKey | quote }}
    secureAuthSalt: {{ .Values.wp.secureAuthSalt | quote }}
