{{- if .Values.dbPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db"
  labels:
    app: "{{ .Release.Name }}-db"
    chart: {{ template "wordpress.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  db-password: {{ .Values.dbPassword | quote }}
{{- end -}}
