{{- if .Values.newrelic.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-newrelic"
  labels:
    app: "{{ .Release.Name }}-wordpress"
    chart: {{ template "wordpress.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  license: {{ .Values.newrelic.license | quote }}
{{- end -}}
