apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-db"
  labels:
    app: "{{ .Release.Name }}-db"
    chart: {{ template "wordpress.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  database: {{ .Values.dbDatabase | quote }}
  username: {{ .Values.dbUsername | quote }}
  password: {{ .Values.dbPassword | quote }}
