{{ if .Values.sentryDsn }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-sentry"
  labels:
    app: "{{ .Release.Name }}-sentry"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sentryDsn: {{ .Values.sentryDsn | quote }}
{{ end }}
