apiVersion: v1
kind: Service
metadata:
  name: {{ template "php.fullname" . }}
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    component: "php"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.php.service.type }}
  ports:
    - port: {{ .Values.php.service.port }}
      targetPort: {{ .Values.php.service.port }}
      protocol: TCP
      name: fastcgi
  selector:
    app: "planet4"
    release: {{ .Release.Name }}
    component: php
    environment: {{ .Values.environment }}
