apiVersion: v1
kind: Service
metadata:
  name: {{ template "exim.fullname" . }}
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    component: "mail"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.exim.service.type }}
  ports:
    - port: {{ .Values.exim.service.port }}
      targetPort: {{ .Values.exim.service.port }}
      protocol: TCP
      name: smtp
  selector:
    app: "planet4"
    release: {{ .Release.Name }}
    component: mail
    environment: {{ .Values.environment }}
