apiVersion: v1
kind: Service
metadata:
  name: {{ template "openresty.fullname" . }}
  labels:
    app: "planet4"
    chart: {{ template "wordpress.chart" . }}
    environment: {{ .Values.environment | quote }}
    component: "proxy"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.openresty.service.type }}
  ports:
    - port: {{ .Values.openresty.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "planet4"
    release: {{ .Release.Name }}
    component: proxy
    environment: {{ .Values.environment }}
